### PR TITLE
Minor UI improvements

### PR DESCRIPTION
**Pull request by alexisrolland**

### CODE REVIEW

**Comment by vilkazz** [comment]
b3f47af commit is not really necessary right now as the payloads are not used. They are there simply because graphql requires you to return something on create/update queries.

**Comment by vilkazz** [comment]
For commit #7ff4d80: Cleanup HTML in forms,  (using </br> instead of <div></div>) is an antipattern as </br> should only be used for content and not layout. I would vote to keep the <div> containers instead. 

https://stackoverflow.com/questions/12717565/using-br-or-div-for-section-break

**Comment by alexisrolland** [comment]
> [b3f47af](https://github.com/mobydq/mobydq/commit/b3f47af5796dbc2e38e028942aecdc16274b7887) commit is not really necessary right now as the payloads are not used. They are there simply because graphql requires you to return something on create/update queries.

Hi @vilkazz ok, so I have simplified the response to return only the id of the object

**Comment by alexisrolland** [comment]
> For commit #7ff4d80: Cleanup HTML in forms, (using 
> instead of
> 
> ) is an antipattern as 
> should only be used for content and not layout. I would vote to keep the
> containers instead.
> https://stackoverflow.com/questions/12717565/using-br-or-div-for-section-break

Ok it's done, I've reverted the changes and replaced the `<br/>` by `</div><div>`

**Pull request merged**
